export function makeInitialState() {
  return {
    screen: 'MENU',
    player: null,
    floor: 1,
    roomIdx: 0,
    enemy: null,
    challenge: null,
    opts: [],
    log: [],
    msg: '',
    msgCls: 'info',
    lastOk: null,
    isSpell: false,
    showHint: false,
    phase: 'ACTION',
    rewardLines: [],
    shopMsg: '',
    nameDraft: '',
    leveledUp: false,
    doorDmg: 0,
    writeAnswer: '',
    usedChallengeIds: [],
    questionsTotal: 0,
    questionsCorrect: 0,
    topicStats: {},
    grade: 9,
    selectedTopics: [],
    learnTopic: null,
    chapterModal: null,
    floors: [],
    baseFloors: [],
    enemies: [],
    loading: false,
  };
}
